# Setup
title:    Ayed
tagline:  Algoritmos y Estructuras de Datos
baseurl:  /ayed
zip:	    https://github.com/FacultadDeIngenieria/ayed/zipball/gh-pages

# About/contact
author:
name:       Algoritmos y Estructuras de Datos
